kind: Namespace
apiVersion: v1
metadata:
  name: prod-ns
  labels:
    name: n7roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prod-ns
  name: n7-test-admin-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: n7-test-admin-rolebinding
  namespace: prod-ns
subjects:
- kind: User
  name: deloitteuser7
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: n7-test-admin-role
  apiGroup: rbac.authorization.k8s.io